<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '三维柔性焊接夹具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '2',
    'cat_name' => '条板式焊接工作台、夹具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '2',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '3',
    'cat_name' => '肘节快速夹具系统',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'MC  加工中心夹具系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '4',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => '气动 液压夹具系列',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => '检具标准件 三座标夹具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => '磨床、线割、电火花夹具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => '球锁快速换模夹具系统',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '9',
    'cat_name' => '定制类工装夹具系统',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '10',
    'cat_name' => '母婴、玩具乐器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '11',
    'cat_name' => '食品饮料、保健食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '12',
    'cat_name' => '彩票、旅行、充值',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '28',
    'cat_name' => '夹具平台',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '22',
    'cat_name' => '支撑角铁',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '49',
    'cat_name' => '定位角尺',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '61',
    'cat_name' => '定位件，转角套',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '40',
    'cat_name' => '锁紧件',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '34',
    'cat_name' => '压紧件',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '13',
    'cat_name' => '附件与辅助材料',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '75',
    'cat_name' => '小管焊接夹具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '69',
    'cat_name' => '与机器人配合夹具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '90',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '93',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '12',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '106',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '16',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '154',
    'cat_name' => '汽车用品',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '16',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '123',
    'cat_name' => '个人护理',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '130',
    'cat_name' => '健康电器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '140',
    'cat_name' => '五金电器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '13',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '80',
    'cat_name' => '大 家 电',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '12',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '171',
    'cat_name' => '垂直式  快速夹具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '200',
    'cat_name' => '水平式  快速夹具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '194',
    'cat_name' => '推拉式  快速夹具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '175',
    'cat_name' => '拉扣式  快速夹具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '185',
    'cat_name' => '焊接组立式快速夹具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '315',
    'cat_name' => '气动肘节快速夹具',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '208',
    'cat_name' => '定位元件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => '3',
  ),
  35 => 
  array (
    'cat_id' => '212',
    'cat_name' => '支撑零件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '3',
    'goods_num' => '2',
  ),
  36 => 
  array (
    'cat_id' => '224',
    'cat_name' => '弹簧柱塞',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '220',
    'cat_name' => '紧固件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '228',
    'cat_name' => '压板元件',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '216',
    'cat_name' => '组合压板',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '318',
    'cat_name' => '侧向压紧',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '319',
    'cat_name' => '精密虎钳基座',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '321',
    'cat_name' => '磁力吸盘',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '90',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '243',
    'cat_name' => '空压        转角缸',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '240',
    'cat_name' => '空压    杠杆缸',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '241',
    'cat_name' => '油压转角缸',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '244',
    'cat_name' => '油压杠杆缸',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '232',
    'cat_name' => '螺纹油缸',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '245',
    'cat_name' => '辅助支撑油缸',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '236',
    'cat_name' => '自锁油缸',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '70',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '316',
    'cat_name' => '气路控制元件',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '80',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '317',
    'cat_name' => '油路控制元件',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '90',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '246',
    'cat_name' => '男装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '250',
    'cat_name' => '女装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '257',
    'cat_name' => '鞋靴',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  55 => 
  array (
    'cat_id' => '254',
    'cat_name' => '运动',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '258',
    'cat_name' => '童装',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '255',
    'cat_name' => '内衣',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '256',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '267',
    'cat_name' => '冲子成型器',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '271',
    'cat_name' => '磨针机',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '269',
    'cat_name' => '砂轮修整器',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '263',
    'cat_name' => '磁台',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '270',
    'cat_name' => '工具万力磨床使用',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '259',
    'cat_name' => '面部护理',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '1',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '268',
    'cat_name' => '线切割夹具',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  66 => 
  array (
    'cat_id' => '272',
    'cat_name' => '基础板',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '280',
    'cat_name' => '夹具板',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '282',
    'cat_name' => '锁紧销',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '279',
    'cat_name' => '附件',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '291',
    'cat_name' => '急救卫生',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '288',
    'cat_name' => '体育娱乐',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '285',
    'cat_name' => '户外装备',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '289',
    'cat_name' => '成人用品',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '286',
    'cat_name' => '运动器械',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '290',
    'cat_name' => '保健器械',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '287',
    'cat_name' => '纤体瑜伽',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '284',
    'cat_name' => '户外鞋服',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '298',
    'cat_name' => '寝具服饰',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '295',
    'cat_name' => '喂养用品',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '292',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '299',
    'cat_name' => '妈妈专区',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '296',
    'cat_name' => '洗护用品',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '293',
    'cat_name' => '营养辅食',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '300',
    'cat_name' => '玩具乐器',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '297',
    'cat_name' => '童车童床',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '294',
    'cat_name' => '尿裤湿巾',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '307',
    'cat_name' => '亚健康',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '304',
    'cat_name' => '粮油调味',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '301',
    'cat_name' => '进口食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '308',
    'cat_name' => '健康礼品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '305',
    'cat_name' => '酒饮冲调',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  92 => 
  array (
    'cat_id' => '302',
    'cat_name' => '地方特产',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '309',
    'cat_name' => '生鲜食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '306',
    'cat_name' => '营养健康',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '303',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '314',
    'cat_name' => '票务',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '311',
    'cat_name' => '机票',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '312',
    'cat_name' => '酒店',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '313',
    'cat_name' => '充值',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '310',
    'cat_name' => '彩票',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '16',
    'cat_name' => '数字杂志',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '17',
    'cat_name' => '多媒体图书',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '14',
    'cat_name' => '电子书',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '15',
    'cat_name' => '网络原创',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '25',
    'cat_name' => '支撑方箱',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '26',
    'cat_name' => '支撑角铁',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '23',
    'cat_name' => '角度器',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '33',
    'cat_name' => 'Φ28系列平台-3维',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '1',
    'goods_num' => 4,
  ),
  109 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'Φ16系列平台-3维',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 4,
  ),
  110 => 
  array (
    'cat_id' => '29',
    'cat_name' => '平板式平台-2维',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  111 => 
  array (
    'cat_id' => '30',
    'cat_name' => '八边形焊接平台',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  112 => 
  array (
    'cat_id' => '31',
    'cat_name' => '支撑脚',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  113 => 
  array (
    'cat_id' => '325',
    'cat_name' => 'Hook Clamps - Recess',
    'measure_unit' => '只',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  114 => 
  array (
    'cat_id' => '35',
    'cat_name' => 'φ16系列压紧件',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'φ28系列压紧件',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '41',
    'cat_name' => '磁性销',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '44',
    'cat_name' => 'φ16锁紧销',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '47',
    'cat_name' => 'φ28锁紧销',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '51',
    'cat_name' => '定位角尺',
    'measure_unit' => '',
    'parent_id' => '49',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '52',
    'cat_name' => '定位平尺',
    'measure_unit' => '',
    'parent_id' => '49',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '53',
    'cat_name' => '平面角尺',
    'measure_unit' => '',
    'parent_id' => '49',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '63',
    'cat_name' => '转角套',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '62',
    'cat_name' => 'V型定位件',
    'measure_unit' => '',
    'parent_id' => '61',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '71',
    'cat_name' => '教育与考试',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  125 => 
  array (
    'cat_id' => '72',
    'cat_name' => '外语学习',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '74',
    'cat_name' => '语言文字',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '70',
    'cat_name' => '教材教辅',
    'measure_unit' => '',
    'parent_id' => '69',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '77',
    'cat_name' => '影印版',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '78',
    'cat_name' => '套装书',
    'measure_unit' => '',
    'parent_id' => '75',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '90',
    'cat_name' => '消毒柜/洗碗机',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '87',
    'cat_name' => '影院',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '84',
    'cat_name' => '冰箱',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  133 => 
  array (
    'cat_id' => '81',
    'cat_name' => '平板电视',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '91',
    'cat_name' => '酒柜/冷柜',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '88',
    'cat_name' => 'DVD',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '85',
    'cat_name' => '空调',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '82',
    'cat_name' => '洗衣机',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '92',
    'cat_name' => '家电配件',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '89',
    'cat_name' => '音响',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '86',
    'cat_name' => '烟机/灶具',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '83',
    'cat_name' => '热水器',
    'measure_unit' => '',
    'parent_id' => '80',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  142 => 
  array (
    'cat_id' => '103',
    'cat_name' => '电熨斗',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '100',
    'cat_name' => '插座',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '97',
    'cat_name' => '吸尘器',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '94',
    'cat_name' => '取暖电器',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '104',
    'cat_name' => '清洁机',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '101',
    'cat_name' => '收录/音机',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '98',
    'cat_name' => '净水设备',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  149 => 
  array (
    'cat_id' => '95',
    'cat_name' => '加湿器',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  150 => 
  array (
    'cat_id' => '105',
    'cat_name' => '饮水机',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '102',
    'cat_name' => '除湿/干衣机',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '99',
    'cat_name' => '电话机',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '96',
    'cat_name' => '净化器',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '109',
    'cat_name' => '电水壶/热水瓶',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '122',
    'cat_name' => '其它厨房电器',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '119',
    'cat_name' => '咖啡机',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '116',
    'cat_name' => '电饼铛/煎烤机',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  158 => 
  array (
    'cat_id' => '113',
    'cat_name' => '电饭煲',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '110',
    'cat_name' => '料理/榨汁机',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  160 => 
  array (
    'cat_id' => '107',
    'cat_name' => '豆浆机',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '120',
    'cat_name' => '电烤箱',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '117',
    'cat_name' => '煮蛋器',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '114',
    'cat_name' => '多用途锅',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '111',
    'cat_name' => '面包机',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '108',
    'cat_name' => '微波炉',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '121',
    'cat_name' => '果蔬解毒机',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '118',
    'cat_name' => '酸奶机',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '115',
    'cat_name' => '电磁炉',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '112',
    'cat_name' => '电压力锅',
    'measure_unit' => '',
    'parent_id' => '106',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '125',
    'cat_name' => '电吹风',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '129',
    'cat_name' => '剃/脱毛器',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '126',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '127',
    'cat_name' => '美容',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '124',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '128',
    'cat_name' => '美发',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '138',
    'cat_name' => '计步器/脂肪检测仪',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '135',
    'cat_name' => '健康秤/厨房秤',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '132',
    'cat_name' => '按摩椅',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '139',
    'cat_name' => '其它健康电器',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '136',
    'cat_name' => '血糖仪',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '133',
    'cat_name' => '足浴盆',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '137',
    'cat_name' => '体温计',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '134',
    'cat_name' => '血压计',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '131',
    'cat_name' => '按摩器',
    'measure_unit' => '',
    'parent_id' => '130',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  185 => 
  array (
    'cat_id' => '141',
    'cat_name' => '电动工具',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '151',
    'cat_name' => '开关/插座',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  187 => 
  array (
    'cat_id' => '148',
    'cat_name' => '淋浴花洒',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  188 => 
  array (
    'cat_id' => '145',
    'cat_name' => '水槽',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  189 => 
  array (
    'cat_id' => '142',
    'cat_name' => '手动工具',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  190 => 
  array (
    'cat_id' => '152',
    'cat_name' => '电线/线缆',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  191 => 
  array (
    'cat_id' => '149',
    'cat_name' => '厨卫五金',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  192 => 
  array (
    'cat_id' => '146',
    'cat_name' => '龙头',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  193 => 
  array (
    'cat_id' => '143',
    'cat_name' => '浴霸/排气扇',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  194 => 
  array (
    'cat_id' => '153',
    'cat_name' => '门铃',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  195 => 
  array (
    'cat_id' => '150',
    'cat_name' => '家具五金',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  196 => 
  array (
    'cat_id' => '147',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  197 => 
  array (
    'cat_id' => '144',
    'cat_name' => '洁身器',
    'measure_unit' => '',
    'parent_id' => '140',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  198 => 
  array (
    'cat_id' => '157',
    'cat_name' => '车载电器',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  199 => 
  array (
    'cat_id' => '170',
    'cat_name' => '安全/应急',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  200 => 
  array (
    'cat_id' => '167',
    'cat_name' => '香水/净化',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  201 => 
  array (
    'cat_id' => '164',
    'cat_name' => '美容',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  202 => 
  array (
    'cat_id' => '161',
    'cat_name' => '脚垫',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  203 => 
  array (
    'cat_id' => '158',
    'cat_name' => '车载电源',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  204 => 
  array (
    'cat_id' => '155',
    'cat_name' => 'GPS',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  205 => 
  array (
    'cat_id' => '168',
    'cat_name' => '安全座椅',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  206 => 
  array (
    'cat_id' => '165',
    'cat_name' => '内饰',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  207 => 
  array (
    'cat_id' => '162',
    'cat_name' => '座垫座套',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  208 => 
  array (
    'cat_id' => '159',
    'cat_name' => '充气/吸尘',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  209 => 
  array (
    'cat_id' => '156',
    'cat_name' => '电子影音',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  210 => 
  array (
    'cat_id' => '169',
    'cat_name' => '自驾装备',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  211 => 
  array (
    'cat_id' => '166',
    'cat_name' => '配件',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  212 => 
  array (
    'cat_id' => '163',
    'cat_name' => '养护',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  213 => 
  array (
    'cat_id' => '160',
    'cat_name' => '冷暖箱',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  214 => 
  array (
    'cat_id' => '173',
    'cat_name' => '对讲机',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  215 => 
  array (
    'cat_id' => '174',
    'cat_name' => '选号入网',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  216 => 
  array (
    'cat_id' => '172',
    'cat_name' => '手机',
    'measure_unit' => '',
    'parent_id' => '171',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  217 => 
  array (
    'cat_id' => '183',
    'cat_name' => '车载',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  218 => 
  array (
    'cat_id' => '180',
    'cat_name' => '贴膜',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  219 => 
  array (
    'cat_id' => '177',
    'cat_name' => '蓝牙耳机',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  220 => 
  array (
    'cat_id' => '184',
    'cat_name' => 'iPhone配件',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  221 => 
  array (
    'cat_id' => '181',
    'cat_name' => '存储卡',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  222 => 
  array (
    'cat_id' => '178',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  223 => 
  array (
    'cat_id' => '182',
    'cat_name' => '保护套',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  224 => 
  array (
    'cat_id' => '179',
    'cat_name' => '手机耳机',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  225 => 
  array (
    'cat_id' => '176',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '175',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  226 => 
  array (
    'cat_id' => '189',
    'cat_name' => '摄像机',
    'measure_unit' => '',
    'parent_id' => '185',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  227 => 
  array (
    'cat_id' => '186',
    'cat_name' => '数码相机',
    'measure_unit' => '',
    'parent_id' => '185',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  228 => 
  array (
    'cat_id' => '193',
    'cat_name' => '单反配件',
    'measure_unit' => '',
    'parent_id' => '185',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  229 => 
  array (
    'cat_id' => '190',
    'cat_name' => '镜头',
    'measure_unit' => '',
    'parent_id' => '185',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  230 => 
  array (
    'cat_id' => '187',
    'cat_name' => '单电/微单相机',
    'measure_unit' => '',
    'parent_id' => '185',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  231 => 
  array (
    'cat_id' => '191',
    'cat_name' => '滤镜',
    'measure_unit' => '',
    'parent_id' => '185',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  232 => 
  array (
    'cat_id' => '188',
    'cat_name' => '单反相机',
    'measure_unit' => '',
    'parent_id' => '185',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  233 => 
  array (
    'cat_id' => '192',
    'cat_name' => '闪光灯/手柄',
    'measure_unit' => '',
    'parent_id' => '185',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  234 => 
  array (
    'cat_id' => '199',
    'cat_name' => '数码包',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  235 => 
  array (
    'cat_id' => '196',
    'cat_name' => '电池/充电器',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  236 => 
  array (
    'cat_id' => '197',
    'cat_name' => '读卡器',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  237 => 
  array (
    'cat_id' => '198',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  238 => 
  array (
    'cat_id' => '195',
    'cat_name' => '存储卡',
    'measure_unit' => '',
    'parent_id' => '194',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  239 => 
  array (
    'cat_id' => '205',
    'cat_name' => '高清播放器',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  240 => 
  array (
    'cat_id' => '202',
    'cat_name' => 'MID',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  241 => 
  array (
    'cat_id' => '206',
    'cat_name' => '电子书',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  242 => 
  array (
    'cat_id' => '203',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  243 => 
  array (
    'cat_id' => '207',
    'cat_name' => '电子词典',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  244 => 
  array (
    'cat_id' => '204',
    'cat_name' => '音箱',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  245 => 
  array (
    'cat_id' => '201',
    'cat_name' => 'MP3/MP4',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  246 => 
  array (
    'cat_id' => '210',
    'cat_name' => '圆柱定位销',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  247 => 
  array (
    'cat_id' => '211',
    'cat_name' => '夹具定位键',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  248 => 
  array (
    'cat_id' => '209',
    'cat_name' => '滑动配合定位销',
    'measure_unit' => '',
    'parent_id' => '208',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  249 => 
  array (
    'cat_id' => '215',
    'cat_name' => '可调螺杆支撑',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  250 => 
  array (
    'cat_id' => '214',
    'cat_name' => '动向钢珠定位螺杆',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  251 => 
  array (
    'cat_id' => '213',
    'cat_name' => '齿面定位支撑',
    'measure_unit' => '',
    'parent_id' => '212',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  252 => 
  array (
    'cat_id' => '218',
    'cat_name' => '键盘',
    'measure_unit' => '',
    'parent_id' => '216',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  253 => 
  array (
    'cat_id' => '219',
    'cat_name' => 'U盘',
    'measure_unit' => '',
    'parent_id' => '216',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  254 => 
  array (
    'cat_id' => '217',
    'cat_name' => '鼠标',
    'measure_unit' => '',
    'parent_id' => '216',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  255 => 
  array (
    'cat_id' => '222',
    'cat_name' => '螺母',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  256 => 
  array (
    'cat_id' => '223',
    'cat_name' => '螺栓',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  257 => 
  array (
    'cat_id' => '221',
    'cat_name' => '垫圈',
    'measure_unit' => '',
    'parent_id' => '220',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  258 => 
  array (
    'cat_id' => '225',
    'cat_name' => '弹簧柱塞',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  259 => 
  array (
    'cat_id' => '226',
    'cat_name' => '球头柱塞',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  260 => 
  array (
    'cat_id' => '227',
    'cat_name' => '压人式柱塞',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  261 => 
  array (
    'cat_id' => '322',
    'cat_name' => '可伸缩型柱塞',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  262 => 
  array (
    'cat_id' => '323',
    'cat_name' => '弹簧挡销',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  263 => 
  array (
    'cat_id' => '324',
    'cat_name' => '弹簧定位塞',
    'measure_unit' => '',
    'parent_id' => '224',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  264 => 
  array (
    'cat_id' => '231',
    'cat_name' => '纸类',
    'measure_unit' => '',
    'parent_id' => '228',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  265 => 
  array (
    'cat_id' => '229',
    'cat_name' => '计算器',
    'measure_unit' => '',
    'parent_id' => '228',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  266 => 
  array (
    'cat_id' => '230',
    'cat_name' => '笔类',
    'measure_unit' => '',
    'parent_id' => '228',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  267 => 
  array (
    'cat_id' => '234',
    'cat_name' => '刀剪砧板',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  268 => 
  array (
    'cat_id' => '235',
    'cat_name' => '收纳保鲜',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  269 => 
  array (
    'cat_id' => '233',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '232',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  270 => 
  array (
    'cat_id' => '237',
    'cat_name' => '床品件套',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  271 => 
  array (
    'cat_id' => '238',
    'cat_name' => '被子',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  272 => 
  array (
    'cat_id' => '239',
    'cat_name' => '枕芯枕套',
    'measure_unit' => '',
    'parent_id' => '236',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  273 => 
  array (
    'cat_id' => '248',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  274 => 
  array (
    'cat_id' => '249',
    'cat_name' => '裤子',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  275 => 
  array (
    'cat_id' => '247',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '246',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  276 => 
  array (
    'cat_id' => '251',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  277 => 
  array (
    'cat_id' => '252',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  278 => 
  array (
    'cat_id' => '253',
    'cat_name' => '裙子',
    'measure_unit' => '',
    'parent_id' => '250',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  279 => 
  array (
    'cat_id' => '261',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  280 => 
  array (
    'cat_id' => '262',
    'cat_name' => '精华露',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  281 => 
  array (
    'cat_id' => '260',
    'cat_name' => '洁面乳',
    'measure_unit' => '',
    'parent_id' => '259',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  282 => 
  array (
    'cat_id' => '264',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  283 => 
  array (
    'cat_id' => '265',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  284 => 
  array (
    'cat_id' => '266',
    'cat_name' => '香薰精油',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  285 => 
  array (
    'cat_id' => '274',
    'cat_name' => '手拿包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  286 => 
  array (
    'cat_id' => '275',
    'cat_name' => '单肩包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  287 => 
  array (
    'cat_id' => '273',
    'cat_name' => '钱包/卡包',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>